receivers:
  otlp:
    protocols:
      http:
        endpoint: "localhost:4318"  # Endpoint cho logs, metrics và spans

exporters:
  debug: {}  # Exporter để hiển thị logs và spans

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      exporters: [debug]
    traces:  # Thêm pipeline cho spans
      receivers: [otlp]
      exporters: [debug]